# ------------------------------------------------------------------------
# SECONDARY BUTTONS
# ------------------------------------------------------------------------
# name - internal label (string)
# priority - position in group (number)
# url - link (string)
# tab - open in new tab (boolean; default: false)
# icon - file name (string; located in "/static/icons" folder)
# disabled - disable link (boolean; default: false)
# visible - show on index page (boolean; default: false)
# ------------------------------------------------------------------------

- button:
  name: "fivem"
  priority: 1
  url: "link-to-fivem"
  tab: true
  icon: "fivem.svg"
  disabled: false
  visible: false 
- button:
  name: "discord"
  priority: 2
  url: "https://discord.gg/xTSA32P"
  tab: true
  icon: "discord.svg"
  disabled: false
  visible: true 
- button:
  name: "reddit"
  priority: 3
  url: "https://www.reddit.com/r/PurpleWorld"
  tab: true
  icon: "reddit.svg"
  disabled: false
  visible: true
- button:
  name: "twitter"
  priority: 4
  url: "https://twitter.com/PurpleWorldRP"
  tab: true
  icon: "twitter.svg"
  disabled: false
  visible: true 
- button:
  name: "patreon"
  priority: 5
  url: "https://www.patreon.com/purpleworld"
  tab: true
  icon: "patreon.svg"
  disabled: false
  visible: true 
  